// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmnOJk9tboRcSO9nAyxY8Vi5ASdTN_4E',
    appId: '1:895200161283:web:f399e8d6a2b59f38d8e836',
    messagingSenderId: '895200161283',
    projectId: 'carimakan-d4629',
    authDomain: 'carimakan-d4629.firebaseapp.com',
    storageBucket: 'carimakan-d4629.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCa-2bnWEnu7QRiM1E3L_zVQb8ouV7-V0',
    appId: '1:895200161283:android:2d2277193fc09b69d8e836',
    messagingSenderId: '895200161283',
    projectId: 'carimakan-d4629',
    storageBucket: 'carimakan-d4629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2h3f5QZ_q7XKIoA_ZnPT37Ulyrh9YzQo',
    appId: '1:895200161283:ios:ca1c6b99134f93bcd8e836',
    messagingSenderId: '895200161283',
    projectId: 'carimakan-d4629',
    storageBucket: 'carimakan-d4629.firebasestorage.app',
    iosBundleId: 'com.example.carimakan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2h3f5QZ_q7XKIoA_ZnPT37Ulyrh9YzQo',
    appId: '1:895200161283:ios:ca1c6b99134f93bcd8e836',
    messagingSenderId: '895200161283',
    projectId: 'carimakan-d4629',
    storageBucket: 'carimakan-d4629.firebasestorage.app',
    iosBundleId: 'com.example.carimakan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzmnOJk9tboRcSO9nAyxY8Vi5ASdTN_4E',
    appId: '1:895200161283:web:7e75cfe45646911ed8e836',
    messagingSenderId: '895200161283',
    projectId: 'carimakan-d4629',
    authDomain: 'carimakan-d4629.firebaseapp.com',
    storageBucket: 'carimakan-d4629.firebasestorage.app',
  );
}
